#!/usr/bin/env node
// Renders every launcher and desktop icon from one drawing of the owl's face.
//
// Run by hand, rarely, like the font scripts beside it:
//
//   node scripts/render-icons.mjs
//   cd apps/desktop && npx tauri icon ../../node_modules/.cache/to-hoot-icons/desktop-1024.png
//
// Needs `rsvg-convert` (librsvg) on the PATH. It writes:
//
//   apps/mobile/icon-source.svg                      the launcher artwork, full bleed
//   apps/desktop/icon-source.svg                     the same face on a rounded square
//   apps/mobile/android/.../drawable/ic_launcher_foreground.xml
//                                                    the face as a vector, for the adaptive icon
//   apps/mobile/android/.../mipmap-*/ic_launcher.png and ic_launcher_round.png
//                                                    Android 7, the only place these are still read
//   node_modules/.cache/to-hoot-icons/desktop-1024.png
//                                                    what `tauri icon` takes as its input
//
// The face is three subpaths on a 32-unit grid, byte for byte the eyes and
// beak `OwlIcon.tsx` and the favicon cut out of their disc. `marks.test.ts`
// reads the two SVG sources back and asserts they still carry this exact path,
// so the drawing lives here once and nowhere else.

import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const res = join(repo, 'apps/mobile/android/app/src/main/res');
const cache = join(repo, 'node_modules/.cache/to-hoot-icons');
mkdirSync(cache, { recursive: true });

/** The eyes and the beak, on the 32-unit grid every mark in the app shares. */
const FACE =
  'M7.6,15.6 a3.5,3.5 0 1,0 7,0 a3.5,3.5 0 1,0 -7,0 Z ' +
  'M17.4,15.6 a3.5,3.5 0 1,0 7,0 a3.5,3.5 0 1,0 -7,0 Z ' +
  'M13.7,20 L18.3,20 L16,24.6 Z';

/** The light-theme accent. It reads on a light wallpaper and on a dark one. */
const CLAY = '#c2603f';
/** The dark theme's paper, which is what the face is drawn in. */
const INK = '#12110f';

/**
 * Where the face sits on a 1024 canvas.
 *
 * The launcher is masked: Android crops the 108dp canvas to a circle, a
 * squircle or a rounded square depending on the launcher, and only the central
 * 66% is safe on all of them. A scale of 26 puts the face at 437px, 65% of that
 * safe circle, with its centre 20px above the middle: a beak points down and a
 * face centred by its box reads as sinking.
 *
 * The desktop icon is not masked, so the face is larger: 504px, half the tile.
 */
const LAUNCHER = { scale: 26, tx: 96, ty: 15 };
const DESKTOP = { scale: 30, tx: 32, ty: -50 };

function face({ scale, tx, ty }) {
  return `  <g transform="translate(${tx} ${ty}) scale(${scale})">\n    <path fill="${INK}" d="${FACE}"/>\n  </g>`;
}

const launcherSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  <title>ToHoot</title>
  <!--
    The launcher artwork, generated by scripts/render-icons.mjs. Edit that
    script, not this file.

    Full bleed, because Android masks it: the clay ground is the adaptive icon's
    background layer and the face is its foreground, so whatever shape the
    launcher cuts, the whole tile is clay with the face inside the safe zone.
  -->
  <rect width="1024" height="1024" fill="${CLAY}"/>
${face(LAUNCHER)}
</svg>
`;

const desktopSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  <title>ToHoot</title>
  <!--
    The desktop icon, generated by scripts/render-icons.mjs. Edit that script,
    not this file.

    A rounded square rather than a full-bleed tile, because nothing masks a
    Linux application icon: the shape has to be the shape.
  -->
  <rect width="1024" height="1024" rx="225" ry="225" fill="${CLAY}"/>
${face(DESKTOP)}
</svg>
`;

/** Android 7 draws these as they are, so they carry their own corners. */
function legacySvg(round) {
  const shape = round
    ? `<circle cx="512" cy="512" r="512" fill="${CLAY}"/>`
    : `<rect width="1024" height="1024" rx="200" ry="200" fill="${CLAY}"/>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  ${shape}
${face(LAUNCHER)}
</svg>
`;
}

/*
 * The adaptive icon's foreground, as a vector drawable in the 108dp viewport.
 *
 * VectorDrawable applies a group's scale and then its translate, exactly as the
 * SVG `translate(...) scale(...)` above does, so the numbers are the launcher
 * numbers divided by 1024/108.
 */
const dp = 108 / 1024;
const fmt = n => String(Math.round(n * 10_000) / 10_000);
const foregroundXml = `<?xml version="1.0" encoding="utf-8"?>
<!--
  The owl's face, as the adaptive icon's foreground and its monochrome layer.
  Generated by scripts/render-icons.mjs from the same three subpaths OwlIcon.tsx
  and the favicon draw; edit that script rather than this file.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <group
        android:scaleX="${fmt(LAUNCHER.scale * dp)}"
        android:scaleY="${fmt(LAUNCHER.scale * dp)}"
        android:translateX="${fmt(LAUNCHER.tx * dp)}"
        android:translateY="${fmt(LAUNCHER.ty * dp)}">
        <path
            android:fillColor="${INK.toUpperCase()}"
            android:pathData="${FACE}" />
    </group>
</vector>
`;

writeFileSync(join(repo, 'apps/mobile/icon-source.svg'), launcherSvg);
writeFileSync(join(repo, 'apps/desktop/icon-source.svg'), desktopSvg);
writeFileSync(join(res, 'drawable/ic_launcher_foreground.xml'), foregroundXml);

function render(svg, size, out) {
  const src = join(cache, `${out.replace(/[\\/]/g, '_')}.svg`);
  writeFileSync(src, svg);
  mkdirSync(dirname(out), { recursive: true });
  execFileSync('rsvg-convert', ['-w', String(size), '-h', String(size), '-o', out, src]);
  console.log(`${size}px  ${out.slice(repo.length + 1)}`);
}

// The legacy densities. mdpi is 48dp at 1x.
for (const [dir, px] of [['mdpi', 48], ['hdpi', 72], ['xhdpi', 96], ['xxhdpi', 144], ['xxxhdpi', 192]]) {
  render(legacySvg(false), px, join(res, `mipmap-${dir}/ic_launcher.png`));
  render(legacySvg(true), px, join(res, `mipmap-${dir}/ic_launcher_round.png`));
}

render(desktopSvg, 1024, join(cache, 'desktop-1024.png'));
console.log(`\nNow: cd apps/desktop && npx tauri icon ${join(cache, 'desktop-1024.png')}`);
