// Builds the bridge into the single plain .js file clasp pushes.
//
// The build step is not optional: clasp v3 dropped TypeScript transpilation, so
// what goes to Google has to be JavaScript already. Bundling also flattens the
// shared protocol module into the output, which matters because the same file
// is what the setup wizard shows a user to paste by hand.

import { build } from 'esbuild';
import { copyFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, 'dist');

const banner = `/**
 * to-hoot calendar bridge.
 *
 * Generated from apps/apps-script/src by esbuild. Do not edit this file: edit
 * the TypeScript source and run \`npm run build -w @to-hoot/apps-script\`.
 *
 * Before this script can answer anything, set a Script Property named
 * TO_HOOT_SECRET (Project Settings -> Script Properties) to the secret the app
 * generated, and enable the Calendar advanced service (Services -> Calendar,
 * v3, identifier "Calendar").
 */`;

// Apps Script calls top-level functions, and the bundle keeps its exports on
// one global object, so the entry points are forwarded by hand.
const footer = `
function doGet(e) {
  return toHootBridge.doGet(e);
}

function doPost(e) {
  return toHootBridge.doPost(e);
}
`;

mkdirSync(outDir, { recursive: true });

await build({
  entryPoints: [resolve(here, 'src/Code.ts')],
  outfile: resolve(outDir, 'Code.js'),
  bundle: true,
  format: 'iife',
  globalName: 'toHootBridge',
  // The Apps Script V8 runtime is current, but nothing here needs newer syntax,
  // and downlevelling costs nothing in a file this size.
  target: 'es2019',
  platform: 'neutral',
  charset: 'utf8',
  legalComments: 'none',
  banner: { js: banner },
  footer: { js: footer },
});

// clasp pushes a directory, and the manifest has to travel with the code.
copyFileSync(resolve(here, 'appsscript.json'), resolve(outDir, 'appsscript.json'));
